spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Ned$tark07
    url: jdbc:mysql://localhost/sbms39
    username: root
  jpa:
    show-sql: true
    
    hibernate:
      ddl-auto: update
    
server:
  port: 8081